export const templates = [
    {
        title: 'Customer Feedback Form',
        description:
            'Collect valuable insights from customers to improve your products and services.',
        author: 'John Doe',
        image: '/test.png',
        topic: 'Customer Experience',
        tags: ['feedback', 'reviews', 'customer satisfaction', 'business'],
    },
    {
        title: 'Event Registration Form',
        description:
            'Register attendees for events and collect essential details for seamless event management.',
        author: 'Jane Smith',
        // // image: 'https://example.com/images/event-registration.jpg',
        topic: 'Event Management',
        tags: ['event', 'registration', 'attendees', 'planning'],
    },
    {
        title: 'Job Application Form',
        description:
            'Streamline your hiring process by gathering resumes and candidate details efficiently.',
        author: 'HR Team',
        // // image: 'https://example.com/images/job-application.jpg',
        topic: 'Recruitment',
        tags: ['job', 'application', 'resume', 'hiring'],
    },
    {
        title: 'Survey Form',
        description:
            'Engage your audience with structured surveys and analyze collected responses.',
        author: 'Marketing Team',
        // // image: 'https://example.com/images/survey-form.jpg',
        topic: 'Market Research',
        tags: ['survey', 'data collection', 'analysis', 'research'],
    },
    {
        title: 'Contact Us Form',
        description:
            'Enable users to send inquiries or support requests with ease.',
        author: 'Support Team',
        // // image: 'https://example.com/images/contact-us.jpg',
        topic: 'Customer Support',
        tags: ['contact', 'support', 'inquiries', 'help'],
    },
    {
        title: 'Newsletter Signup Form',
        description:
            'Allow users to subscribe to your newsletter and stay updated with the latest news.',
        author: 'Marketing Team',
        // image: 'https://example.com/images/newsletter-signup.jpg',
        topic: 'Email Marketing',
        tags: ['newsletter', 'subscription', 'email', 'marketing'],
    },
    {
        title: 'Product Order Form',
        description:
            'Simplify the purchasing process by letting customers place product orders online.',
        author: 'Sales Team',
        // // image: 'https://example.com/images/product-order.jpg',
        topic: 'E-commerce',
        tags: ['order', 'product', 'purchase', 'checkout'],
    },
    {
        title: 'Bug Report Form',
        description:
            'Help users report issues or bugs in your application for faster resolution.',
        author: 'Development Team',
        // // image: 'https://example.com/images/bug-report.jpg',
        topic: 'Software Development',
        tags: ['bug', 'issue', 'report', 'debugging'],
    },
    // {
    //     title: 'Course Enrollment Form',
    //     description:
    //         'Allow students to enroll in courses and collect essential registration details.',
    //     author: 'Education Team',
    //     // // image: 'https://example.com/images/course-enrollment.jpg',
    //     topic: 'Education',
    //     tags: ['enrollment', 'course', 'student', 'learning'],
    // },
    // {
    //     title: 'Donation Form',
    //     description:
    //         'Make it easy for users to contribute to your cause with a simple donation form.',
    //     author: 'Non-Profit Organization',
    //     // // image: 'https://example.com/images/donation-form.jpg',
    //     topic: 'Fundraising',
    //     tags: ['donation', 'charity', 'fundraising', 'non-profit'],
    // },
];

export const tags = [
    { value: 'feedback', count: 45 },
    { value: 'reviews', count: 38 },
    { value: 'customer satisfaction', count: 33 },
    { value: 'business', count: 40 },
    { value: 'event', count: 50 },
    { value: 'registration', count: 35 },
    { value: 'attendees', count: 28 },
    { value: 'planning', count: 30 },
    { value: 'job', count: 42 },
    { value: 'application', count: 37 },
    { value: 'resume', count: 25 },
    { value: 'hiring', count: 32 },
    { value: 'survey', count: 48 },
    { value: 'data collection', count: 29 },
    { value: 'analysis', count: 31 },
    { value: 'research', count: 26 },
    { value: 'contact', count: 41 },
    { value: 'support', count: 36 },
    { value: 'inquiries', count: 34 },
    { value: 'help', count: 27 },
    { value: 'newsletter', count: 39 },
    { value: 'subscription', count: 24 },
    { value: 'email', count: 30 },
    { value: 'marketing', count: 35 },
    { value: 'order', count: 43 },
    { value: 'product', count: 29 },
    { value: 'purchase', count: 31 },
    { value: 'checkout', count: 22 },
    { value: 'bug', count: 46 },
    { value: 'issue', count: 33 },
    { value: 'report', count: 37 },
    { value: 'debugging', count: 28 },
    { value: 'enrollment', count: 44 },
    { value: 'course', count: 39 },
    { value: 'student', count: 36 },
    { value: 'learning', count: 32 },
    { value: 'donation', count: 50 },
    { value: 'charity', count: 47 },
    { value: 'fundraising', count: 42 },
    { value: 'non-profit', count: 38 },
];
